# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "yarn"
    directories:
      - "*"
    schedule: # Check for updates daily
      interval: "daily"

    versioning-strategy: bump # Update any dependency whose major version is different

    open-pull-requests-limit: 10 # Allow Dependabot to create pull requests automatically
    ignore: # Ignore specific dependencies or versions
      - "@types/react-dom": "^16.13.1"
  - package-ecosystem: "yarn"
    directories:
      - "node_modules"
    schedule: # Check for updates weekly
      interval: "weekly"
    versioning-strategy: patch
    # open-pull-requests-limit: 5

    assignees: # Allow Dependabot to assign reviewers to pull requests
      - "@sseworld"
      # - "@janedoe"

    labels: # Use labels to categorize pull requests
      - "dependabot"
      - "version-update"
